#!/usr/bin/env bash

set -e 
set -o pipefail

APPARATUS_INSTALLDIR="${HOME}/Workspace/personal"

function install_macos {

  # install brew
  which -s brew &>/dev/null || { /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"; }

  # install brew packages
  brew install \
    git \
    tig \
    neovim \
    stow \
    fzf \
    ripgrep \
    direnv \
    bat \
    jq \
    navi \
    romkatv/powerlevel10k/powerlevel10k \
    zsh-syntax-highlighting \
    zsh-autosuggestions

  # fonts
  brew tap homebrew/cask-fonts
  brew install --cask font-jetbrains-mono-nerd-font

  # fzf key bindings
  $(brew --prefix)/opt/fzf/install --key-bindings --no-completion --no-bash --no-fish --no-update-rc

  # kitty
  curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
}

function stow_macos {
  stow --restow --target="$HOME" zsh
  stow --restow --target="$HOME" git
  stow --restow --target="$HOME" tig
  stow --restow --target="$HOME" powerlevel10k
  stow --restow --target="$HOME/.config" kitty
  stow --restow --target="$HOME/.config" karabiner
  stow --restow --target="$HOME/.config" nvim
  stow --restow --target="$HOME/Google Drive/My Drive/Notes" obsidian

  mkdir -p "$HOME/Library/Application Support/navi"
  stow --restow --target="$HOME/Library/Application Support/navi" navi
}

function unstow_macos {
  stow --delete --target="$HOME" zsh
  stow --delete --target="$HOME" git
  stow --delete --target="$HOME" tig
  stow --delete --target="$HOME" powerlevel10k
  stow --delete --target="$HOME/.config" kitty
  stow --delete --target="$HOME/.config" karabiner
  stow --delete --target="$HOME/.config" nvim
  stow --delete --target="$HOME/Library/Application Support/navi" navi
  stow --delete --target="$HOME/Google Drive/Notes" obsidian
}

function apparatus {
  if [ -d "${APPARATUS_INSTALLDIR}" ]; then
    echo "will not clone apparatus; it already exists in $APPARATUS_INSTALLDIR"
    return
  fi

  pushd . >/dev/null
  mkdir -p $APPARATUS_INSTALLDIR
  cd $APPARATUS_INSTALLDIR
  git clone git@github.com:liouk/apparatus.git
  popd >/dev/null
}

function main {

  if [[ "$OSTYPE" == "darwin"* ]]; then
    install_macos "$@"
    apparatus "$@"
    stow_macos "$@"

  else
    echo "error: unexpected os"
    exit 1

  fi
}

main "$@"
