require("plugin_config.alpha")
require("plugin_config.leap")
require("plugin_config.nvim-tree")
require("plugin_config.telescope")
require("plugin_config.blamer")
require("plugin_config.gitgutter")
require("plugin_config.barbar")
