# Configure zsh prompt
source ~/.zsh/.zsh_prompt

# Aliases
source ~/.zsh/.zsh_aliases

# Display archey
#archey -o

# PATH definitions
export PATH="$HOME/.rbenv/bin:/usr/local/sbin:$PATH"
export EDITOR="vim"

eval "$(rbenv init -)"

# Futurae
export PATH="$GOPATH/bin:$PATH"
export FUTURAE="/Users/ilias/Workspace/futurae"

# direnv
eval "$(direnv hook zsh)"

[[ -s "/Users/ilias/.gvm/scripts/gvm" ]] && source "/Users/ilias/.gvm/scripts/gvm"

# Misc
export LC_ALL=en_US.UTF-8

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit

# fzf
[ -f ~/.fzf.bash ] && source ~/.fzf.bash
