#!/bin/bash

# Escape codes

        RED="%F{red}"
     YELLOW="%F{yellow}"
      GREEN="%F{green}"
       BLUE="%F{blue}"
     PURPLE="%F{magenta}"
  LIGHT_RED="%F{9}"
LIGHT_GREEN="%F{10}"
      WHITE="%F{white}"
 LIGHT_GRAY="%F{15}"
 COLOR_NONE="%f"
     BG_RED="%K{red}"
    BG_BLUE="%K{blue}"
    BG_NONE="%k"
    NEWLINE=$'\n'
    PATH_SH=%~

# determine git branch name
function parse_git_branch(){
    if [ -d .git ] || git rev-parse --git-dir > /dev/null 2>&1 ; then
        git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/{\1} /'
    fi
}

# Determine the branch/state information for this git repository.
function set_git_branch() {
    # Get the name of the branch.
    branch=$(parse_git_branch)

    # Set the final branch string.
    BRANCH="${RED}${branch}${COLOR_NONE}"
}

# Return the prompt symbol to use, colorized based on the return value of the
# previous command.
function set_prompt_symbol () {
    SYMBOL="λ"

    if test -n "$SSH_TTY" || test -n "$SSH_CLIENT" ; then
        SYMBOL="$"
    fi

    if [[ `whoami` == "root" ]] ; then
        SYMBOL="#"
    fi

    if test $1 -eq 0 ; then
        PROMPT_SYMBOL=$SYMBOL
    else
        PROMPT_SYMBOL="${LIGHT_RED}${SYMBOL}${COLOR_NONE}"
    fi
}

# Set the hostname, highlighting the background if in ssh
function set_host () {
    P_HOST=%m
    if test -n "$SSH_TTY" || test -n "$SSH_CLIENT" ; then
        P_HOST="${BG_BLUE}${WHITE}${P_HOST}${COLOR_NONE}${BG_NONE}"
    fi
}

# Set the username and the hostname
function set_user () {
    P_USER=`whoami`
    P_USER="${P_USER}@"
    if [[ ${P_USER} == "root@" ]] ; then
        P_USER="${BG_RED}${WHITE}${P_USER}${COLOR_NONE}${BG_NONE}"
    fi
}

# Display blackbox info in the prompt if it exists
function set_blackbox() {
    BLACKBOX=
    [[ "${BLACKBOX_STATUS:-}" ]] && BLACKBOX="${BLACKBOX_STATUS} "
}

# Set the full bash prompt.
function set_bash_prompt () {
    # Set the PROMPT_SYMBOL variable. We do this first so we don't lose the
    # return value of the last command.
    set_prompt_symbol $?

    # Set the P_HOST variable.
    set_host

    # Set the P_USER variable.
    set_user

    # Set the BRANCH variable.
    set_git_branch

    # Set the blackbox status
    set_blackbox

    # Set the bash prompt variable.
    PS1="${NEWLINE}${GREEN}${P_USER}${P_HOST}${COLOR_NONE}:${YELLOW}${PATH_SH}${COLOR_NONE}${NEWLINE}${PYTHON_VIRTUALENV}${BRANCH}${BLACKBOX}${PROMPT_SYMBOL} "
}


# Tell bash to execute this function just before displaying its prompt.
PROMPT_COMMAND=set_bash_prompt
