# Configure zsh prompt
source ~/.zsh/.zsh_prompt
precmd() { eval "$PROMPT_COMMAND" }

export EDITOR="vim"

# Aliases
source ~/.zsh/.zsh_aliases

# Futurae
export PATH="$GOPATH/bin:$PATH"
export FUTURAE="/Users/ilias/Workspace/futurae"

[[ -s "/Users/ilias/.gvm/scripts/gvm" ]] && source "/Users/ilias/.gvm/scripts/gvm"

# Misc
export LC_ALL=en_US.UTF-8

# Load Git completion
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.bash
fpath=(~/.zsh $fpath)

autoload -Uz compinit && compinit

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# brew
eval $(/opt/homebrew/bin/brew shellenv)

# rbenv
export PATH="$HOME/.rbenv/bin:/usr/local/sbin:$PATH"
eval "$(rbenv init -)"

# direnv
eval "$(direnv hook zsh)"
